global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'watch_prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  # Example job for VPS Watch-Node_exporter
  - job_name: 'example.ro' # You can put here your domain
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
      - targets: ['postgres-exporter:9187']
      - targets: ['jmx-exporter:6688']
      - targets: ['cadvisor:8080']

  # Websites
  - job_name: 'Websites'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://example.ro
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'